language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: g1G6N8OJ08KVN7mZ4tMpiOwSqb4apHXi94zMiZcB73vsdPJtsvmZNa1HTkbpK6U5HZB8Tk3TSNfWyOpg5Jy/POJbs8DizhS6p6Cm9gPL1uxFPT+ncm7Pl4ptx8cEVxBdPAvEEd58PfiBz6Ge5b4LRzNlYtHk0HnMhmARdv6JE0GTFNASFBOimC4RbRB55ep7xJ9Fptcvo1j+I3Eb+37r0My64tVxciiA3fn8lMngGElZ4epyaOsIB53ceuHgqh0Kpi+hvrlUC0ExFnW/e4wPO1wfvk81XYcds7HYKmPyxf/6Fo+Y+42wybut33fjQppPPLmPNygj0xiuLRk2W+hIk7KljgkZTtYbl7hIhVtDBBTji2sc1S7beAmS3pNfMIbbgoit2QCrp5xcJPdQHWbVz802PlGUVBvqy3Kl4mW1KQ5D15vDMl3xUXh0rtxoQHPzKFePlC8lwgrp9ajlok3t500z3lkKCcG17232NQhHbAoZdsPcyE1NQefUVh6HOb7h29vspW8ys0SkbzmuU3OzKdH2xC5NzaL0cEZororztFulncBofiS//LTvhA/0VXnpDfScbfmVeihrl5zFz0zNkijnwS2j+2Y/v+4FggN0HyjHWrfyYygbDoK2gjnNK7QX0ePOZfVKYrd88qPWO073JFg50oKNMt+Z639RpLi2Egc=
  app: froom2bustimes
